---
title: "full-TcmI-analysis"
author: "Francine Camacho"
date: "2/25/2019"
output:
  html_document: 
    smart: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/francinecamacho/Google Drive/T2PKS-paper/computational_analysis/synthetic_genomes/HMM-analysis/TcmI/version-2/')
```


```{r, message = FALSE }
#load libraries
require(tidyverse)
```

### Load full profiled cyclase TcmI HMMs for synthetic genomes
```{r, message = FALSE}
#load TcmI HMM data and recode sampleType for the complexity of the synthetic sample (#of genomes in samples)
cyclase_TcmI <- read_delim("combined-cyclase_TcmI-full-synthetic_genomes-results.txt",col_names = F, delim = "\t") 
names(cyclase_TcmI) <- c("readID", "sampleType", "sampleID", "cyclaseType", "HMMScore")
```

##### Remove the reading frame information from the readID. 
```{r,message=FALSE}
# Function to aggregate identitical sample reads located at different reading frames 
# and take the frame with the highest HMM score
formatHMM<-function(hmmdf){
  hmmdfRecoded <- separate(hmmdf, readID, into = c("readIDOnly","F_R_read_frame"), sep = "/", extra = "merge")
  hmmdfRecoded_FR <- separate(hmmdfRecoded, F_R_read_frame, into = c("F_R","frameNumb"), sep = "_", extra = "merge")
  hmmdfRecodedDF<- within(hmmdfRecoded_FR, readID <- paste(readIDOnly,F_R, sep='/'))
  hmmdfRecodedDFUnique<-aggregate(HMMScore ~ readID + sampleID + sampleType + cyclaseType , hmmdfRecodedDF, max)
  colnames(hmmdfRecodedDFUnique)<-c("readID","Sample", "sampleType", "cyclaseType","HMMScore")
  return(hmmdfRecodedDFUnique)
}

#Keep duplicated reads if they are in different reads
cyclaseTcmI_recoded<-formatHMM(cyclase_TcmI)
```

##### Load the BLAST data for T2PKS cyclase genes against our synthetic dataset. 
```{r, message=FALSE}
#BLAST True positive reads mapped to the T2PKS cyclases genes 
cyclase_metadata <- read_tsv("../../T2PKS-pos_genomes-cyclase_gene-metadata.txt", col_names = T) %>% filter(used_in_synthetic_metagenome == "Y") %>% select(c(11:9))

# BLAST filtered data 
t2pksBlastDF <- read_delim("../../../T2PKS-TP-reads/t2pksBlastDF_filter-results.txt", col_names = T, delim = "\t") %>% inner_join(.,cyclase_metadata, by= c("qseqid" = "nucl_cyclase_target_name") )%>% filter(cyclase_type == "TcmI") 

```

##### Determine manual cutoffs for each interval within the model
```{r, message=FALSE}
compareCyclaseReads<-function(cyclaseDF, blastDF){
  
  names(blastDF)[names(blastDF)=="sseqid"] <-"readID"
  names(blastDF)[names(blastDF)=="qseqid"] <-"bgcName"
  names(cyclaseDF)[names(cyclaseDF)=="cyclaseType"] <-"cyclase_type"
  
  common_reads <- blastDF %>% inner_join(.,cyclaseDF) %>% select(-c(HMMScore))
  common_reads$readCheck<-"common-read"
  
  hmm_unique_reads <- cyclaseDF %>% anti_join(.,blastDF)
  hmm_unique_reads$readCheck<-"hmm-unique-read"
  blast_unique_reads <- blastDF %>% anti_join(.,cyclaseDF)
  blast_unique_reads$readCheck<-"blast-unique-read"
  
  blast_common_data <- rbind(common_reads, blast_unique_reads)
  allCyclases_TP<- blast_common_data %>% full_join(.,hmm_unique_reads) 
  allCyclases_TP$bgcName[is.na(allCyclases_TP$bgcName)]<-"hmm-unique-read"
  return(allCyclases_TP %>% select(-c(HMMScore)))
  
}
##############################################################################################
cyclaseTcmI_bin <- compareCyclaseReads(cyclaseTcmI_recoded,t2pksBlastDF)
names(cyclaseTcmI_bin)[names(cyclaseTcmI_bin)=="cyclase_type"] <-"cyclaseType"
```

##### Trying to determine the HMM cutoffs; calculate median 

```{r, message=FALSE}

compare_reads <- function(hmm_df, blast_df){
  names(blast_df)[names(blast_df)=="sseqid"] <-"readID"
  names(blast_df)[names(blast_df)=="qseqid"] <-"bgcName"
  names(hmm_df)[names(hmm_df)=="cyclaseType"] <-"cyclase_type"
  
  common_reads <- hmm_df %>% semi_join(.,blast_df) 
  common_reads$readCheck<-"common-read"
  hmm_unique_reads <- hmm_df %>% anti_join(.,blast_df)
  hmm_unique_reads$readCheck<-"hmm-unique-read"
  compared_data <- rbind(common_reads, hmm_unique_reads)
  return(compared_data)
}

compare_reads(cyclaseTcmI_recoded, t2pksBlastDF) %>% filter(readCheck == "common-read") %>% mutate(medianScore = round(median(HMMScore))) %>% distinct(readCheck, medianScore) %>% ungroup()

```

### Apply different HMM Scores cutoff to the HMM dataset
```{r,message=FALSE}
#Filter OxyN data with cutoffs to compare to BLAST interval reads 
TcmI_filtered_median <- cyclaseTcmI_recoded %>% filter(HMMScore >=30) %>% inner_join(.,cyclaseTcmI_bin)

#TcmI_filtered_median  %>% filter(readCheck == "hmm-unique-read") %>% separate(readID, c("scaffold_id", "rest_id"), sep = "-", remove = F) %>% distinct(scaffold_id)

pks_genomes_median_check <-c("JOFH01000019.1", "gi|529222834|ref|NC_021985.1|", "gi|640930959|gb|JJOH01000095.1|", "gi|640932211|gb|JJOH01000028.1|")

remaining_hmm_TcmI_pos_median_check <- TcmI_filtered_median %>% filter(readCheck == "hmm-unique-read") %>% separate(readID, c("scaffold_id", "rest_id"), sep = "-", remove = F) %>% filter(scaffold_id %in% pks_genomes_median_check)

####################################################################################
TcmI_filtered_median_subfive<- cyclaseTcmI_recoded %>% filter(HMMScore >=25) %>% inner_join(.,cyclaseTcmI_bin)

#TcmI_filtered_median_subfive  %>% filter(readCheck == "hmm-unique-read") %>% separate(readID, c("scaffold_id", "rest_id"), sep = "-", remove = F) %>% distinct(scaffold_id)

pks_genomes_subfive_check <-c("gi|529222834|ref|NC_021985.1|", "JOFH01000019.1", "gi|640932211|gb|JJOH01000028.1|", "AZXI01000013.1", "gi|640930959|gb|JJOH01000095.1|", "AZXI01000002.1")
remaining_hmm_TcmI_pos_subfive_check <- TcmI_filtered_median_subfive %>% filter(readCheck == "hmm-unique-read") %>% separate(readID, c("scaffold_id", "rest_id"), sep = "-", remove = F) %>% filter(scaffold_id %in% pks_genomes_subfive_check)
####################################################################################                                 
TcmI_filtered_median_plusfive <- cyclaseTcmI_recoded %>% filter(HMMScore>=35) %>% inner_join(.,cyclaseTcmI_bin)

#TcmI_filtered_median_plusfive  %>% filter(readCheck == "hmm-unique-read") %>% separate(readID, c("scaffold_id", "rest_id"), sep = "-", remove = F) %>% distinct(scaffold_id)
pks_genomes_plusfive_check <- c("JOFH01000019.1", "gi|529222834|ref|NC_021985.1|", "gi|640932211|gb|JJOH01000028.1|", "gi|640930959|gb|JJOH01000095.1|")
remaining_hmm_TcmI_pos_plusfive_check <- TcmI_filtered_median_plusfive %>% filter(readCheck == "hmm-unique-read") %>% separate(readID, c("scaffold_id", "rest_id"), sep = "-", remove = F) %>% filter(scaffold_id %in% pks_genomes_plusfive_check)

```


```{r}
#Function to parse out HMM unique reads for each sample. 
parseReads <- function(HMMdf, modelName, dirname){
  setwd(dirname)
  samples<-unique(HMMdf$Sample)
  for (s in 1:length(samples)){
    currentSample<-samples[s]
    currentSampleResults<- HMMdf %>% filter(Sample == currentSample)
    currentSampleReads<- unique(currentSampleResults$readID)
    fileName<-paste0(currentSample,paste("-",modelName,"-hmm_unique",sep =""), ".txt", sep ="")
    write.table(currentSampleReads,fileName, quote = F, row.names = F, col.names = F )
  }
}

#parseReads(remaining_hmm_TcmI_pos_median_check, "cyclaseTcmI", "/Users/francinecamacho/Google Drive/T2PKS-paper/computational_analysis/synthetic_genomes/HMM-analysis/TcmI/version-2/full_model-analysis/hmm-unique-analysis/median_score/")

#parseReads(remaining_hmm_TcmI_pos_subfive_check, "cyclaseTcmI", "/Users/francinecamacho/Google Drive/T2PKS-paper/computational_analysis/synthetic_genomes/HMM-analysis/TcmI/version-2/full_model-analysis/hmm-unique-analysis/minus_five_score")

#parseReads(remaining_hmm_TcmI_pos_plusfive_check, "cyclaseTcmI", "/Users/francinecamacho/Google Drive/T2PKS-paper/computational_analysis/synthetic_genomes/HMM-analysis/TcmI/version-2/full_model-analysis/hmm-unique-analysis/plus_five_score/")

```

```{r, message=FALSE}

calculate_F1 <- function(df){
  TP <- df %>% filter(readCheck == "common-read") %>% nrow()
  FP <- df %>% filter(readCheck == "hmm-unique-read") %>% nrow()
  FN <- df %>% filter(readCheck == "blast-unique-read") %>% nrow()
  F1_metric <- (2*TP)/((2*TP)+FP+FN)
  print(F1_metric)
  return(F1_metric)
  
  
}

remove_TcmI_reads_subfive  <- c("JOFH01000019.1-21230/1", "JOFH01000019.1-22422/1", "JOFH01000019.1-13038/1", "gi|640932211|gb|JJOH01000028.1|-1466/2","gi|640932211|gb|JJOH01000028.1|-352/2","gi|640932211|gb|JJOH01000028.1|-5334/2" ,"gi|640932211|gb|JJOH01000028.1|-4710/1", "JOFH01000019.1-7282/2", "JOFH01000019.1-8106/2", "gi|640930959|gb|JJOH01000095.1|-13190/1", "JOFH01000019.1-15742/1", "JOFH01000019.1-11556/2", "JOFH01000019.1-4016/1", "gi|640930959|gb|JJOH01000095.1|-16936/2", "gi|640932211|gb|JJOH01000028.1|-4436/1", "gi|640932211|gb|JJOH01000028.1|-4340/1", "gi|640930959|gb|JJOH01000095.1|-12402/2", "JOFH01000019.1-12402/1", "JOFH01000019.1-11550/1", "JOFH01000019.1-10810/2", "JOFH01000019.1-15100/2")

remove_TcmI_reads_median<- c("JOFH01000019.1-21230/1", "JOFH01000019.1-22422/1", "gi|640932211|gb|JJOH01000028.1|-352/2", "gi|640932211|gb|JJOH01000028.1|-4710/1", "gi|640930959|gb|JJOH01000095.1|-13190/1", "JOFH01000019.1-4016/1", "gi|640930959|gb|JJOH01000095.1|-16936/2", "gi|640932211|gb|JJOH01000028.1|-4436/1", "gi|640932211|gb|JJOH01000028.1|-4340/1", "gi|640930959|gb|JJOH01000095.1|-12402/2", "JOFH01000019.1-12402/1", "JOFH01000019.1-11550/1", "JOFH01000019.1-10810/2", "JOFH01000019.1-14064/2", "JOFH01000019.1-15100/2")
remove_TcmI_reads_plusfive <-c("JOFH01000019.1-21230/1", "gi|640932211|gb|JJOH01000028.1|-352/2", "gi|640932211|gb|JJOH01000028.1|-4710/1", "gi|640930959|gb|JJOH01000095.1|-13190/1", "gi|640930959|gb|JJOH01000095.1|-16936/2", "gi|640932211|gb|JJOH01000028.1|-4436/1", "JOFH01000019.1-10810/2", "JOFH01000019.1-15100/2")

TcmI_f1_cutoff_median <- calculate_F1(compareCyclaseReads(cyclaseTcmI_recoded %>% filter(!readID %in% remove_TcmI_reads_median)  %>% filter(HMMScore >=30),t2pksBlastDF)) #0.621642
TcmI_f1_cutoff_plusfive <- calculate_F1(compareCyclaseReads(cyclaseTcmI_recoded %>% filter(!readID %in% remove_TcmI_reads_plusfive) %>% filter(HMMScore >=35),t2pksBlastDF)) #0.4304598
TcmI_f1_cutoff_subfive <- calculate_F1(compareCyclaseReads(cyclaseTcmI_recoded %>% filter(!readID %in% remove_TcmI_reads_subfive) %>% filter(HMMScore >=25),t2pksBlastDF)) #0.7641951
```

```{r}
sessionInfo()
```


