#!/bin/bash

set -o errexit
set -o nounset

# handle input file
readonly INPUT_DIR=$(readlink -f $1)
shift

# handle output file
readonly OUTPUT_DIR=$(readlink -f $1)
shift

# Links within the container
readonly CONTAINER_SRC_DIR=/input
readonly CONTAINER_DST_DIR=/output

if [ ! -d ${OUTPUT_DIR} ]; then
    mkdir -p ${OUTPUT_DIR}
fi

docker run \
    --volume ${INPUT_DIR}:${CONTAINER_SRC_DIR}:ro \
    --volume ${OUTPUT_DIR}:${CONTAINER_DST_DIR}:rw \
    --detach=false \
    --rm \
    metabgc:latest $@
